### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Eivlys** [fisheepx/douban-to-imdb#12]
第一次执行会在处理到第十几页的时候提示：
```
Traceback (most recent call last):
  File "/Users/sylvie/Repo/douban-to-imdb/douban_to_csv.py", line 144, in <module>
    export(sys.argv[1])
  File "/Users/sylvie/Repo/douban-to-imdb/douban_to_csv.py", line 113, in export
    info.extend(get_info(url))
TypeError: 'NoneType' object is not iterable
```
之后再次执行每次都提示：
```
总共 1 页
开始处理第 1 页...
Traceback (most recent call last):
  File "/Users/sylvie/Repo/douban-to-imdb/douban_to_csv.py", line 144, in <module>
    export(sys.argv[1])
  File "/Users/sylvie/Repo/douban-to-imdb/douban_to_csv.py", line 113, in export
    info.extend(get_info(url))
TypeError: 'NoneType' object is not iterable
```

切换终端代理也会有同样的报错

**Comment by f-is-h** [comment]
@Eivlys 
之前有其它人反应豆瓣会限制相同IP访问的页数，
如果遇到这种情况建议更换IP后再尝试。

✳️参照下说明，可以从特定日期之后导出

**Comment by Eivlys** [comment]
> @Eivlys 之前有其它人反应豆瓣会限制相同IP访问的页数， 如果遇到这种情况建议更换IP后再尝试。
> 
> ✳️参照下说明，可以从特定日期之后导出

好的 我试下 谢谢

**Comment by tom2almighty** [comment]
将代码 79 行 get_info 函数下 else 后 return 值改为 '[]' 可以解决
